dist: bionic
language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt update -y
  - sudo apt install -y googletest ninja-build
script:
  - mkdir -p build
  - cd build
  - cmake .. -GNinja -DGTEST_ROOT=/usr/local
  - ninja
  - ctest
