dist: bionic
language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt update -y
  - sudo apt install -y googletest ninja-build
script:
  - bash scripts/install-googletest.sh
  - bash scripts/build-morton.sh
  - ctest
