dist: bionic
language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt update -y
  - sudo apt install -y libgtest-dev ninja-build
script:
  - mkdir -p build
  - cd build
  - cmake .. -GNinja
  - ninja
  - ctest
