dist: bionic
language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt install googletest ninja-build
script:
  - mkdir -p build
  - cd build
  - cmake .. -GNinja
  - ninja
  - ctest
